development:
  stripe_secret_key: 'pk_test_geufYBE595yJfHOBtx1ukSGt'
  stripe_publishable_key: 'pk_test_SAfpkFB2WVKLbQVukGCTVq5Z'

production:
  stripe_secret_key: 'pk_test_geufYBE595yJfHOBtx1ukSGt'
stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'
